# Generated by Django 2.0.7 on 2018-08-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telebot', '0002_auto_20180803_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bot_user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bot_user',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bot_user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
