# Generated by Django 2.0.7 on 2018-08-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telebot', '0003_auto_20180803_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot_user',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='bot_user',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
