# Generated by Django 2.0.7 on 2018-08-10 17:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Telebot', '0004_auto_20180803_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time_sent', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
