# Generated by Django 2.0.7 on 2018-07-30 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_auto_20180730_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
