# Generated by Django 2.0.7 on 2018-08-09 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Telebot', '0004_auto_20180803_1545'),
        ('Tasks', '0005_auto_20180730_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Telebot.Bot_user'),
        ),
    ]
